<?php

$title = 'Add new album';
$this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$this->form->setAttribute('action', $this->url('album', ['action' => 'add']));
$this->form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('artist'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();